### ISSUE TITLE
DEV: checklist for before the new release 0.3.2

### ISSUE THREAD

**Issue by st3107** [xpdAcq/PDFstream#37]
- [x] Get the maintainer rights of the package

- [x] Set the org to xpdAcq on codecov

- [x] Change the url of the badges

- [x] A script to install the extra packages in a github repo if the user has the token

- [x] CI passed

- [x] Rever script to auto-update the nsls-ii-forge
